# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft
minecraft_version=1.21.11
minecraft_version_range=[1.21.11,]
minecraft_support_version=1.21.11+

# Forge
forge_id=forge
forge_version=52.1.10
forge_version_range=[52,)

mapping_channel=official
mapping_version=1.21.1

# NeoForge
neoforge_id=neoforge
neogradle.subsystems.parchment.minecraftVersion=1.21.11
neogradle.subsystems.parchment.mappingsVersion=2025.12.20
neo_version=21.11.38-beta
neo_version_range=[21,)
neo_loader_version_range=[1,)

# Mod
mod_group_id=dev.xcolorful.cgcconfig
mod_id=cgcconfig
mod_name=CGC Config Addon
mod_license=GPL-3.0-only
mod_version=0.0.4
mod_credits=Based on TaCZ and its contributors; continued by XiaoColorful
mod_authors=XiaoColorful
mod_description=Config addon for Custom Gun Continued

mod_issue_url=https://github.com/XColorful/CGC-Config-Addon/issues
mod_display_url=https://github.com/XColorful/CGC-Config-Addon/wiki
mod_logo_file=logo.png

pack_description=CGC Config Addon resources
pack_format=15

# Dependencies
customgun_version_range=[0.0.5,)
customgun_local=../libs/customgun-0.0.5-neoforge-1.21.11.jar
cloth_config_version=21.11.153
cloth_config_version_range=[21.11.153,)
cloth_config_maven=me.shedaniel.cloth:cloth-config-neoforge

# CompileOnly
