# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft
minecraft_version=1.20.1
minecraft_version_range=[1.20,1.20.2)

# Forge
forge_id=forge
forge_version=47.4.16
forge_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

# Mod
mod_group_id=dev.xcolorful.cgcconfig
mod_id=cgcconfig
mod_name=CGC Config Addon
mod_license=GPL-3.0-only
mod_version=0.0.0
mod_credits=Based on TaCZ and its contributors; continued by XiaoColorful
mod_authors=XiaoColorful
mod_description=Config addon for Custom Gun Continued

mod_issue_url=https://github.com/XColorful/CGC-Config-Addon/issues
mod_display_url=https://github.com/XColorful/CGC-Config-Addon/wiki
mod_logo_file=logo.png

pack_description=CGC Config Addon resources
pack_format=15

# Dependencies
customgun_version_range=[0.0.3,)
customgun_local=../libs/customgun-0.0.3-forge-1.20.1.jar

# CompileOnly
