plugins {
    id 'java-library'
    id 'net.neoforged.gradle.userdev' version '7.0.116'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    implementation "${customgun_maven}"
    implementation "${cloth_config_maven}:${cloth_config_version}"
}

jar {
    archiveBaseName.set(mod_id)
    archiveVersion.set(mod_version)
    archiveClassifier.set("core")
}